MAJOR = 4
MINOR = 6
PATCH = 0
FORK = "pf"

VERSION = (MAJOR, MINOR, PATCH, FORK)
NUMERIC_VERSION = (MAJOR, MINOR, PATCH)
VERSION_STR = f"{MAJOR}.{MINOR}.{PATCH}.{FORK}"
NUMERIC_VERSION_STR = f"{MAJOR}.{MINOR}.{PATCH}"
